### ISSUE TITLE
Improper player null check breaks player-link-less placeholder reads

### ISSUE THREAD

**Issue by mcmonkey4eva** [PlaceholderAPI-Expansions/SuperbVote-Expansion#5]
This code: https://github.com/PlaceholderAPI/SuperbVote-Expansion/blob/de7ba2d4ab052fd5ad22a9ee02eb0b7e6575864f/src/main/java/com/extendedclip/papi/expansion/superbvote/SuperbVoteExpansion.java#L67-L70

Breaks the `top_voter_*` placeholders whenever there isn't a player link - even though they don't need one.

The `p == null` check should only be applied to `votes` and `has_voted` (as those are the only two that require a player link).

**Comment by darbyjack** [comment]
Fixed via https://github.com/PlaceholderAPI/SuperbVote-Expansion/commit/719bc4f546e340da4e70dba48df0addb3a7ebdd4
